### ISSUE TITLE
Make Nate project owner, instead of Admin, for three projects

### ISSUE THREAD

**Issue by farmernate** [ExperimentalFarmNetwork/efn-drupal#107]
I'm listed as the owner of three of my projects, but not for another three (Chinquapin, Sorghum, and Jojoba). Also, while I'm on the subject, can we change the word "owner" to "organizer" across the board? THANKS! @multilectical @dafeder

**Comment by multilectical** [comment]
for the record and our memory, this can be done by an admin by making another user admin and then deleting the owner. (project > members > add member (make admin). then remove prev owner)
