### ISSUE TITLE
Project updates page

### ISSUE THREAD

**Issue by dafeder** [ExperimentalFarmNetwork/efn-drupal#11]
As a project participant I want to see all the important information for a project when I navigate to its main landing page

## Acceptance criteria

* Page includes project post list (actual functionality part of issue #17)
* Page includes basic project description and metadata, with link to full description page if necesarry
* Page includes list of participants
* Page includes basic profile info for project lead with link to their profile
* Non-members of the project group do not have access
* Is a tab/sub-item of main project page, so `/group/[gid]/updates`

**Comment by farmernate** [comment]
Participants have ability to post to page as well? Would be nice. (Related to issue #17 )

**Comment by farmernate** [comment]
Great.
