### ISSUE TITLE
"Create project" button disappeared!

### ISSUE THREAD

**Issue by farmernate** [ExperimentalFarmNetwork/efn-drupal#114]

**Comment by multilectical** [comment]
This happened some time ago for mobile. It was an element I thought was probably only going to be used for logged in users on desktops.

**Comment by farmernate** [comment]
Didn't realize. It's gone on my desktop too right now. (I think it should
probably be there for mobile as well, even though it would be really
annoying to do on mobile.)

**Comment by multilectical** [comment]
Your desktop is safari, right?

**Comment by multilectical** [comment]
And are you logged in?

**Comment by farmernate** [comment]
Yes, using safari, and logged in. (Sorry for delayed reply!)

**Comment by farmernate** [comment]
Just logged in on Chrome, and the "New Project" button is there. Still not
on Safari.

**Comment by farmernate** [comment]
Apparently this is a problem on Firefox as well (according to a new member).
