### ISSUE TITLE
"Project owner" shuffling problem

### ISSUE THREAD

**Issue by farmernate** [ExperimentalFarmNetwork/efn-drupal#115]
The newest person to join a project is automatically becoming the "Project owner." This was a big problem before and I thought it was fixed, but it's not. May only be with recently added projects though.

**Comment by dafeder** [comment]
Taking a look

**Comment by multilectical** [comment]
@farmernate : I can't replicate this thing at all. 

Could you let me know the user and what group they joined? I created a user on the site and tried joining numerous groups, none of which I appeared as owner and none of which I could edit.

Could you replicate this? if so where?

**Comment by multilectical** [comment]
works now :)
