### ISSUE TITLE
Project details page

### ISSUE THREAD

**Issue by dafeder** [ExperimentalFarmNetwork/efn-drupal#19]
As a project participant I want to refer to the full description and other details of the project.

## Acceptance criteria

* Full project details probably will not fit on the main project landing page with all the other info we're showing, so a separate page is needed for full description & metadata
* Should have clear context and easy navigation back to project landing page
* This is what you see at URL `/group/[gid]`
* Details page has tabs, the updates page is a tab/sub-item

**Comment by farmernate** [comment]
Cool.
