### ISSUE TITLE
Auto node wants arrays, but null given :(

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#26]
Let's switch to auto_entitylabel which has a d8 release listed on it's page. (https://www.drupal.org/node/2747425)

fyi, typical error:

`Warning: array_splice() expects parameter 1 to be array, null given in auto_nodetitle_form_node_form_alter() (line 33 of modules/auto_nodetitle/auto_nodetitle.module).
auto_nodetitle_form_node_form_alter(Array, Object, 'node_project_update_gnode-form_form') (Line: 501)
Drupal\Core\Extension\ModuleHandler->alter('form', Array, Object, 'node_project_update_gnode-form_form') (Line: 818)
Drupal\Core\Form\FormBuilder->prepareForm('node_project_update_gnode-form_form', Array, Object) (Line: 272)
Drupal\Core\Form\FormBuilder->buildForm('node_project_update_gnode-form_form', Object) (Line: 48)
Drupal\Core\Entity\EntityFormBuilder->getForm(Object, 'gnode-form', Array) (Line: 131)
Drupal\gnode\Controller\GroupNodeWizardController->addForm(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`

**Comment by multilectical** [comment]
looks like maintainer nuked content on auto_entitylabel module. will procrastinate on this for a few days. see if something shows up again.. 

https://www.drupal.org/node/2832453

**Comment by dafeder** [comment]
You can just check out an earlier release or earlier commit from git for now, shouldn't block anything
