### ISSUE TITLE
Ajax comments not displaying w/o pageload

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#31]
Comments on project pages submit, but don't reload group page to show that it's happened. Either need to figure out how to ajax show comments right away or ajax load the form?

**Comment by dafeder** [comment]
It looks like this is working now, sort of? I can't post a second comment but my first one works.

**Comment by multilectical** [comment]
fixed by showing full nodes in view instead of teasers
