### ISSUE TITLE
Improve/remove Breadcrumbs

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#32]
Breadcrumbs aren't helpful here. They either need work or removing. I propose remove them for now...
eg: for /group/2/join:  G2 High Altitude Coffee Crop / Join group G2 High Altitude Coffee Crop
or for group/2/node/create/project_update: G2 High Altitude Coffee Crop /  Create node /  Create Project Update in G2 High Altitude Coffee Crop

**Comment by dafeder** [comment]
We decided to remove them.
