### ISSUE TITLE
change project location to researcher location in Projects

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#40]

**Comment by multilectical** [comment]
Do we want to do this? Maybe 2 locations in case different or maybe in Project form prepopulate with author zip?

**Comment by farmernate** [comment]
Yeah, I think prepopulating with researcher's zip and calling it
"researcher location" instead of "project location" definitely makes most
sense. Thanks!

**Comment by multilectical** [comment]
Cool just committed [master 0618f0a] which changes the field label, still needed to pull in the user value at node creation.
