### ISSUE TITLE
Descriptive Tags don't add group to taxonomy

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#45]
When adding a tag, the tag is added to the taxonomy, but the group tagged isn't added to the tag??

eg: in /admin/structure/taxonomy/manage/tags/overview jojoba should include /group/2, but doesn't.

**Comment by dafeder** [comment]
The taxonomy relationship is correct; this is cause the dumb Drupal taxonomy term page only shows nodes. Some ideas for overriding this to show other entity types here: https://www.drupal.org/node/1016942
