### ISSUE TITLE
Make group pages to replace taxonomy

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#51]
because taxonomy pages need to show content

**Comment by multilectical** [comment]
@farmernate was about to make this tagging thing work to show pages of cards show up when you click the tags buttons, but wondering now if this actually makes sense or not.  are the tags actually useful? judging from info entered on the projects, it may be more confusing. Does it make sense to use this? It might make more sense to just use the project type field.

**Comment by multilectical** [comment]
oops duplicate of #45

**Comment by farmernate** [comment]
I guess because the whole description will be searchable too (as easily as
tags) they're probably not necessary and just extra work (for you and for
the people filling out profiles). I don't mind losing them.
