### ISSUE TITLE
Group content: skip final step

### ISSUE THREAD

**Issue by dafeder** [ExperimentalFarmNetwork/efn-drupal#55]
Creating group posts should be a one-step process, no "final step" with extra fields that make no sense to user.

See this issue: https://www.drupal.org/node/2819595

**Comment by multilectical** [comment]
moving comment over here:
logged in as onion@riseup.net:
clicking Join group on https://www.experimentalfarmnetwork.org/project/8 goes to
https://www.experimentalfarmnetwork.org/group/8/join that ugly in between page, I thought we had gotten rid of, then brings me to the empty in between node:
https://www.experimentalfarmnetwork.org/group/8/content/21

@dafeder, did you write something to go into the efn_users module, but forget to commit? or have a lead on this issue? i seem to remember something.

**Comment by multilectical** [comment]
https://www.drupal.org/project/group/releases/8.x-1.0-beta5 might be a fix here, but promises: Massive overhaul regarding UX for adding content to a group . going to try on a branch...

**Comment by multilectical** [comment]
#65 fixes join. 

another line segment in the form_alter in efn_users.module:32 ??
