### ISSUE TITLE
Default user image for Personal Profile

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#56]
Because it looks lame when empty :hankey:

**Comment by dafeder** [comment]
I added some conditionals to remove the broken images, but they look kind of weird

**Comment by multilectical** [comment]
@farmernate: what do you think we should use for a default user image? ie: when a user refuses to upload an image to their profile... was thinking maybe one of Briana's seeds or a stock default pic like I might paste below
![user-default-img](https://cloud.githubusercontent.com/assets/1326270/26169763/d3bf4538-3b0c-11e7-8148-72bfa479e83b.png) or
![no_img_board_0](https://cloud.githubusercontent.com/assets/1326270/26169778/dd159786-3b0c-11e7-8ccf-1594b0b1652d.jpg)
