### ISSUE TITLE
Show/hide other field in Volunteer Profile 

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#61]
a little js to show other field

**Comment by dafeder** [comment]
Not sure what you mean here?

**Comment by multilectical** [comment]
On the form,  there is the big text field below the 'other' checkbox. It probably should be hidden until other checkbox is checked. Could be a line of js or that module that dues that from UI..

**Comment by dafeder** [comment]
We actually had the select_or_other module installed but a) I believe we were talking with Nate about changing that form structure a bit and b) that module was causing an error. Let's see if some of those fields can be eliminated or made into more "details" fields instead... but if we need to re-enable select_or_other we'll need to adress the form validation error it was causing.

**Comment by multilectical** [comment]
i did it with js so we don't need to deal with module bugs, are we using that module for other stuff?
