### ISSUE TITLE
Problems joining groups

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#65]
One person said she got an error when attempting to join two projects (mayapples and the seed saving & increases one), despite having made a profile and everything.

**Comment by multilectical** [comment]
logged in as onion@riseup.net: 
clicking Join group on https://www.experimentalfarmnetwork.org/project/8 goes to 
https://www.experimentalfarmnetwork.org/group/8/join that ugly in between page, I thought we had gotten rid of, then brings me to the empty in between node: 
https://www.experimentalfarmnetwork.org/group/8/content/21

@dafeder, did you write something to go into the efn_users module, but forget to commit? or have a lead on this issue? i seem to remember something.

**Comment by multilectical** [comment]
No errors now :) but after joining reroutes back to user page. It should probably go right to the group instead. Maybe a just hook_form_alter?

**Comment by dafeder** [comment]
Yes meant to make some tickets about that - both the user and content forms
redirect to the wrong place.

**Comment by multilectical** [comment]
redirect fixed but issue was sort of vague ?!?!?!?!
