### ISSUE TITLE
Fix "Save and make default" button on profile form

### ISSUE THREAD

**Issue by dafeder** [ExperimentalFarmNetwork/efn-drupal#70]
Profile forms are showing both the "save" and "save and make default" buttons, which don't make sense because we don't allow multiple profiles. This suggests the issue is fixed but looking at the code for the current version it looks like some of the fix has been reverted and regressed. Investigate further, possibly re-open issue on d.o.

https://www.drupal.org/node/2799669

**Comment by multilectical** [comment]
i form altered it away for now
